### ISSUE TITLE
Use ORM

### ISSUE THREAD

**Issue by vganshin** [ifmo-kis/foodtohome#8]
Одно из требований — использовать ОРМ. Если переехать на тот же хибер, то необходимость в поддержке sql-скрипта отпадет.

**Comment by NikolayVasiletskij** [comment]
Если дело касается забивкой данными, то да, согласен, но насчет создания бд - хибер очень плохо делает некоторую работу (ex. таблица без первичного ключа - избыточные данные), но на создание бд скрипт уже написан, поэтому оставляем так.

**Comment by vganshin** [comment]
ОРМ — обязательное требование в принципе. Т.е. в коде бизнес-логики не должно быть sql.

**Comment by NikolayVasiletskij** [comment]
Ну это бизнес-логика. Создание таблиц же не должно являться её частью, вроде как. Использование hbm2ddl в продакшене не комильфо, говорят..

**Comment by vganshin** [comment]
Ну, у меня возникали сложности с Django ORM при миграциях. Но пока они все были решаемые. Ок. Я просто обращаю внимание, что нужно будет показать ОРМ и только.)
